// user
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

// pictures
export const PICTURES_INIT = 'PICTURES_INIT'
export const PICTURES_ADD = 'PICTURES_ADD'
export const PICTURES_DELETE = 'PICTURES_DELETE'

// blog
export const BLOG_ARTICLES_INIT = 'BLOG_ARTICLES_INIT'
export const BLOG_ARTICLES_ADD = 'BLOG_ARTICLES_ADD'
export const BLOG_ARTICLES_EDIT = 'BLOG_ARTICLES_EDIT'
export const BLOG_ARTICLES_DELETE = 'BLOG_ARTICLES_DELETE'
export const BLOG_CLASSIFICATION_INIT = 'BLOG_CLASSIFICATION_INIT'
export const BLOG_CLASSIFICATION_ADD = 'BLOG_CLASSIFICATION_ADD'
export const BLOG_CLASSIFICATION_EDIT = 'BLOG_CLASSIFICATION_EDIT'
export const BLOG_CLASSIFICATION_DELETE = 'BLOG_CLASSIFICATION_DELETE'
